language: generic
sudo: false
branches:
  only:
  - master
  - "/^\\d+\\.\\d+.*$/"
os:
- linux
install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -p $HOME/miniconda
- source $HOME/miniconda/bin/activate
- conda config --append channels ae5-admin
- conda install conda conda-build conda-verify anaconda-client --yes
- conda info -a
script:
- conda build conda-recipe --python 3.6
deploy:
- provider: script
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
  script: anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin $HOME/miniconda/conda-bld/*/*.tar.bz2
    --force
- provider: script
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
  script: anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin --label
    dev $HOME/miniconda/conda-bld/*/*.tar.bz2 --force
env:
  global:
  - PYTHONUNBUFFERED=1
  - secure: FH/bc4Xv2Sn8QyentIPW8OMNe2flAHTflaoSI3k0Lz3BcNCwSaG4huw9U2PgtuXf8vLDTsUcwmhHq/XOer6ILk15mDEOBJkGcRlkTprTmgfuSC2hthvnQXb8u1EPJ31FY2mLfEC7YVB8wMTEH9rey8tIQpteO1vFqVLC0yB8rA1BCiTxuVdnVAMzKsruhDlj7HHWRTE6VPx7skzziQRf4M4BQO6QvwfyKQ2YLQXYAQVwHKVDL5Lofdd67Bl8kQI9SuE7dWE6THQHF3KGyejUR2sAtIkMa5/Pu5aws/yR5EVQ4xJVWzZeaDVFfgks3vgwApgjhW7sAQWXv6Gg+OcX7g5cSeS83nODE8o5/FW81nCDKaFrRBGl40ME5cLJlxU/J13yLom6dKOxOnlgNf9ID1AP8XAMF0hDDWlFjjKImoX1s3VptiHDP2nSqrK7M8azv/NBJVa3zWCcYqrwO+d0stsqUtEBkEYuaNh9KeY/xxWhh3xKUtW70jCvgf7M8x7FYsChc4/gU2NXCOlPEExYXbe854+fpKKh6hpaHx3JWt/KQ0NRwEIOJGfSX6Zm8f6wKkPczpuJgPQQZpdaQy13mtnQuf8TE9+/L4ozF+PVgRuFRfODWCCrH5h0/3s4gwjwxnYPbqt5UhcW8kYck3JnM3PiOqXOVmY3mznvbUtsjp4=
  - secure: iV5wiq0ugdwqKJrPEqBlMtiu0U1oKvke0xMiO73hMQtzT5fP/1svYJLjJYATEnPjXHqI/fD9emLA1UkrjfWw6VveBcdQc42+aApzo2FBcuLBDdY6l3ifSn1SC+HnItVpwGb0z4IXVW0oqTy485ahHbASJQLMKJ1hXHs7zwS+PQ+H9RxQjdUDYa97BR/9iuw5itT2lPMaPYileS8IuLXZMOZ1rFV6G7nlfO+dTlZhWubGjiFkWRGMb92bV6AGJp/IzKnNgLwHdZAItilg0L/b0izIrfyKqHj9qA+L6tO26aPwTODrVe3Cn02tpfBlARXIkELpr256IcvTpnEPMP6Tt6KOFor7VIYmS+3YospFpldu/CGEZ+dtzXAWWE+nNtLWPhgxnR6MA1JOGO9SAVz5jP4UOg0ZXLW3mDE8tBhvMmLNYlJAqldzd2kSgj9w9BWxjEKTe61RvRcjxJqCN243zDPB4CtetyukdJNr5W9Eg39oCaZXPTqySYAI2tCPTMDyFNJPO+NJP53Oh0l5Ps1pFUHzlp0ijRFG28QLCDk7Bb0AzPwJjTqcyH75Gjt7dQswnoUMTRRu6x+XIgxBoG6lb2lFWF31K6yIDZ+ihUxnDrtpRF9nGVIfyl2JWTAyaRKwqvsN25lM/l3XPVLBpnuqH0SgQ/EMxlXHe7a6TWNmpYM=
  - secure: uFFkoju8bQDV1K6zfIXAaGe6iR3AhpAUHwJcNg0KV7Da90csvJQALOQcEyzYP06zxH+xr8ltQceyxe9IMCgoQypKmX0PrQku6uBHnG5NevC0HbweqOfIRzvo67NjDYsPDpTkRDq9nWrJAm0Xux5g/dYmJQLFyRAY2dlTIcN18PcmnN12rkIZUuSxC25Sc/TmepYTE9drvCqhuWfPYX53Qa3Lbb27uilxarKXRif2uCIXHeIeXgZpnbqoF59GAbytJv5qZXKZEvWIAWPgTiF5IZhx+bpOcZ0HpR0eGGnR5ar3+3QjmdzsV86HisyWv1uOQhlpH9JPhLslmLhQkT7mo0V9w0HhpqGNtFX/qEYagR+GOc5PsImbxrGTmcvtOvFtGARd4tSehuxhtfDVnasMPhxASRQynkbqCzX6MxuIwsx4ks7wyybQrEmM0VInvn6CpZPzu0laaMuB7Xlxo9Su9rwT0S0l8aGEcY1FdjGxu0Np7zNngvsuRVYUw4UbiOD0zH+2ssVVZ5qZMH5J3W8VJIUMCD3SIaU63nOo1vBT7pTZt9ArBSSR7azo1rEyTL3bsPhOsnuwvqQi+sBR2/f37TZPVxipHvEnDFRy7Si/kMYAdi5noxFen8wX1KYH/lNpmrkoLAMXoP6FrsJHdUC9Xdgw66MCj1Z9twzJuYuzf6Q=
