name: anaconda.enterprise.server.sdk
channels:
  - defaults
  - conda-forge
  - joshburt
dependencies:
  - black
  - conda-build
  - black-jupyter
  - jupyter
  - coverage
  - isort
  - pydantic
  - pylint
  - python=3.10.8
  - python-dotenv
  - setuptools
  - anaconda-client
  - shapeandshare.command.runner
  - anaconda.enterprise.server.common.sdk>=0.1
  - anaconda.enterprise.server.contracts>=0.2
