{% set data = load_setup_py_data() %}

package:
  name: ae5-tools
  version: {{ data.get('version').lstrip('v') }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - ae5 = ae5_tools.cli.main:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python>=3.8
    - python-dateutil>=2.7
    - click>=7
    - click-repl
    - requests
    - aiohttp
    - pandas
    - pydantic>=2

about:
  home: https://github.com/Anaconda-Platform/ae5-tools
  summary: 'Command-line manipulation of Anaconda Enterprise 5.'
  license: BSD
  license_file: LICENSE
