{% set name = "anaconda.enterprise.server.sdk" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python>=3.9
    - setuptools
  run:
    - python>=3.9
    - pydantic
    - anaconda.enterprise.server.common.sdk
    - anaconda.enterprise.server.contracts

about:
  home: https://github.com/shapeandshare/anaconda.enterprise.server.sdk
  summary: "Anaconda Enterprise Server SDK"
  license: BSD
  license_file: LICENSE
