{% set name = "anaconda.enterprise.sdk" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python>=3.9
    - setuptools
  run:
    - python>=3.9
    - requests
    - aiohttp
    - pydantic

about:
  home: https://github.com/shapeandshare/anaconda.enterprise.sdk
  summary: "Anaconda Enterprise SDK"
  license: BSD
  license_file: LICENSE
