name: Pull Request and Dev Publish
on:
  pull_request:
    branches:
      - master
jobs:
  package:
    runs-on: self-hosted
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
        fetch-depth: 0
    - name: Linting
      run: |
        anaconda-project run lint
    - name: Build the package
      env:
        AE5_HOSTNAME: aip.anaconda.com
        AE5_USERNAME: tooltest
        AE5_PASSWORD: ${{ secrets.AE5_PASSWORD }}
        AE5_ADMIN_USERNAME: admin
        AE5_ADMIN_PASSWORD: ${{ secrets.AE5_ADMIN_PASSWORD }}
        AE5_K8S_ENDPOINT: ssh:centos
        AE5_K8S_PORT: 23456
      run: |
        source $CONDA/etc/profile.d/conda.sh
        rm -f $CONDA/conda-bld/noarch/ae5-tools-*.tar.bz2
        conda install -y conda-build conda-verify anaconda-client
        conda build conda-recipe
    - name: Upload to anaconda.org (Dev Build)
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        source $CONDA/bin/activate
        anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin --label dev $CONDA/conda-bld/noarch/ae5-tools-*.tar.bz2 --force
