name: Pull Request and Dev Publish
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      # https://github.com/conda-incubator/setup-miniconda
      uses: conda-incubator/setup-miniconda@11b562958363ec5770fef326fe8ef0366f8cbf8a # v3
      with:
        channels: defaults
        auto-activate-base: true
        activate-environment: github.action
        environment-file: environment.github.yml
    - name: Conda Info
      run: |
        conda info
    - name: Anaconda Project Setup
      run: |
        anaconda-project prepare --env-spec default
    - name: Linting
      run: |
        anaconda-project run lint
    - name: Run Unit Tests
      run: |
        anaconda-project run test:unit
    - name: Build Conda Package
      run: |
        mkdir build
        conda build conda-recipe --debug --no-anaconda-upload --no-test --output-folder build
    - name: Run Integration Tests
      run: |
        anaconda-project run test:integration:slipstream
    - name: Upload to anaconda.org (Dev Build)
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin --label dev build/noarch/ae5-tools-*.tar.bz2 --force
