name: Pull Request and Dev Publish
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
#    runs-on: self-hosted
#    runs-on: self-hosted-amd64-small-privileged
#    runs-on: self-hosted-amd64-large-privileged-on-demand-storage
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      # https://github.com/conda-incubator/setup-miniconda
      uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3 # v2
      with:
        channels: defaults
        auto-activate-base: true
        activate-environment: github.action
        environment-file: environment.github.yml
    - name: Conda Info
      run: |
        conda info
    - name: Anaconda Project Setup
      run: |
        anaconda-project prepare --env-spec development
    - name: Linting
      run: |
        anaconda-project run lint
    - name: Run Unit Tests
      run: |
        anaconda-project run test:unit
    - name: Build the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        rm -f $CONDA/conda-bld/noarch/ae5-tools-*.tar.bz2
        conda install -y conda-build conda-verify anaconda-client
        conda build conda-recipe
    - name: Run Integration Tests
      run: |
        anaconda-project run test:integration:slipstream
#    - name: Run System Tests
#      env:
#        AE5_HOSTNAME: dev1.ae.anacondaconnect.com
#        CI: true
#      run: |
#        anaconda-project run test:system
    - name: Upload to anaconda.org (Dev Build)
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        source $CONDA/bin/activate
        anaconda --verbose --token $ANACONDA_TOKEN upload --user ae5-admin --label dev $CONDA/conda-bld/noarch/ae5-tools-*.tar.bz2 --force
